#!/bin/bash
# Install macos-screenshot-pipeline for the current GUI user.
# Idempotent. Safe to re-run.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
HOME_DIR="${HOME}"
LIBEXEC="${HOME_DIR}/.local/libexec/macos-screenshot-pipeline"
CONFIG_DIR="${HOME_DIR}/.config/macos-screenshot-pipeline"
CONFIG_FILE="${CONFIG_DIR}/config.env"
APPS="${HOME_DIR}/Applications"
AGENTS="${HOME_DIR}/Library/LaunchAgents"
UID_NUM="$(id -u)"
DOMAIN="gui/${UID_NUM}"

LABEL_CAPTURE="com.travisjneuman.screenshotpipeline.capture"
LABEL_HOTKEY="com.travisjneuman.screenshotpipeline.hotkey"
LEGACY_CAPTURE="dev.neuman.screenshot-to-photos"
LEGACY_HOTKEY="dev.neuman.screenshot-edit-hotkey"

WITH_HOTKEY=1
WITH_PHOTOS=1
KEEP_STAGING=0
SKIP_PREFS=0
STAGING="${HOME_DIR}/Pictures/Camera Roll"
CAPTION="Screenshot"
KEYWORD="Screenshot"

usage() {
  cat <<'EOF'
Usage: ./install.sh [options]

  --no-hotkey       Skip building/loading the ⌘⇧E hotkey agent
  --no-photos       Clipboard only; do not import into Photos
  --keep-staging    Do not delete staging files after success
  --staging PATH    Staging directory (default: ~/Pictures/Camera Roll)
  --caption STR     Photos caption/description (default: Screenshot)
  --keyword STR     Photos keyword (default: Screenshot)
  --skip-prefs      Do not write com.apple.screencapture defaults
  -h, --help        Show this help

After install, grant Accessibility to "Screenshot Pipeline Hotkey" if using the hotkey agent.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-hotkey) WITH_HOTKEY=0; shift ;;
    --no-photos) WITH_PHOTOS=0; shift ;;
    --keep-staging) KEEP_STAGING=1; shift ;;
    --staging)
      STAGING="${2:-}"
      [[ -n "$STAGING" ]] || { echo "error: --staging needs a path" >&2; exit 2; }
      shift 2
      ;;
    --caption)
      CAPTION="${2:-}"
      [[ -n "$CAPTION" ]] || { echo "error: --caption needs a value" >&2; exit 2; }
      shift 2
      ;;
    --keyword)
      KEYWORD="${2:-}"
      [[ -n "$KEYWORD" ]] || { echo "error: --keyword needs a value" >&2; exit 2; }
      shift 2
      ;;
    --skip-prefs) SKIP_PREFS=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "error: unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

# Expand leading ~
case "$STAGING" in
  "~/"*) STAGING="${HOME_DIR}/${STAGING#~/}" ;;
  "~") STAGING="${HOME_DIR}" ;;
esac

DELETE_STAGING=1
if [[ "$KEEP_STAGING" == "1" ]]; then
  DELETE_STAGING=0
elif [[ "$WITH_PHOTOS" != "1" ]]; then
  # Safer default: keep files when Photos import is off.
  DELETE_STAGING=0
fi

IMPORT_PHOTOS=0
[[ "$WITH_PHOTOS" == "1" ]] && IMPORT_PHOTOS=1

mkdir -p "$LIBEXEC" "$CONFIG_DIR" "$APPS" "$AGENTS" "$STAGING" \
  "${HOME_DIR}/Library/Logs" \
  "${HOME_DIR}/Library/Caches/macos-screenshot-pipeline" \
  "${HOME_DIR}/.local/state/macos-screenshot-pipeline"

echo "==> Writing config: $CONFIG_FILE"
cat >"$CONFIG_FILE" <<EOF
# macos-screenshot-pipeline — user config (generated by install.sh)
STAGING_DIR="${STAGING}"
CAPTION="${CAPTION}"
KEYWORD="${KEYWORD}"
IMPORT_PHOTOS=${IMPORT_PHOTOS}
DELETE_STAGING_ON_SUCCESS=${DELETE_STAGING}
ENABLE_HDR=1
SHOW_THUMBNAIL=0
EOF

echo "==> Installing scripts → $LIBEXEC"
cp -f "$ROOT/bin/process.sh" "$LIBEXEC/"
cp -f "$ROOT/bin/edit-clipboard-in-preview.sh" "$LIBEXEC/"
cp -f "$ROOT/bin/hotkey-agent.swift" "$LIBEXEC/"
cp -f "$ROOT/bin/apply-screencapture-prefs.sh" "$LIBEXEC/"
chmod 755 "$LIBEXEC/process.sh" \
  "$LIBEXEC/edit-clipboard-in-preview.sh" \
  "$LIBEXEC/apply-screencapture-prefs.sh"

if [[ "$SKIP_PREFS" != "1" ]]; then
  echo "==> Applying screencapture preferences"
  SCREENSHOT_STAGING="$STAGING" STAGING_DIR="$STAGING" \
    bash "$LIBEXEC/apply-screencapture-prefs.sh"
else
  echo "==> Skipping screencapture preferences (--skip-prefs)"
fi

# Avoid two capture agents on the same staging folder.
legacy_note=0
if launchctl print "${DOMAIN}/${LEGACY_CAPTURE}" >/dev/null 2>&1; then
  echo "==> Unloading legacy capture agent (${LEGACY_CAPTURE}) to avoid double-processing"
  launchctl bootout "${DOMAIN}/${LEGACY_CAPTURE}" 2>/dev/null || true
  legacy_note=1
fi
if [[ "$WITH_HOTKEY" == "1" ]] && launchctl print "${DOMAIN}/${LEGACY_HOTKEY}" >/dev/null 2>&1; then
  echo "==> Unloading legacy hotkey agent (${LEGACY_HOTKEY}) — same default chord ⌘⇧E"
  launchctl bootout "${DOMAIN}/${LEGACY_HOTKEY}" 2>/dev/null || true
  legacy_note=1
fi

if [[ "$WITH_HOTKEY" == "1" ]]; then
  echo "==> Building hotkey agent (requires Xcode CLT / swiftc)"
  if ! command -v swiftc >/dev/null 2>&1; then
    echo "error: swiftc not found. Install Xcode Command Line Tools:" >&2
    echo "  xcode-select --install" >&2
    echo "Or re-run with --no-hotkey." >&2
    exit 1
  fi
  swiftc -O -o "$LIBEXEC/hotkey-agent" "$LIBEXEC/hotkey-agent.swift"
  AGENT_APP="${APPS}/Screenshot Pipeline Hotkey.app"
  rm -rf "$AGENT_APP"
  mkdir -p "$AGENT_APP/Contents/MacOS"
  cp "$LIBEXEC/hotkey-agent" "$AGENT_APP/Contents/MacOS/Screenshot Pipeline Hotkey"
  cat >"$AGENT_APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key><string>Screenshot Pipeline Hotkey</string>
  <key>CFBundleIdentifier</key><string>com.travisjneuman.screenshotpipeline.hotkey</string>
  <key>CFBundleName</key><string>Screenshot Pipeline Hotkey</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>LSUIElement</key><true/>
  <key>NSHumanReadableCopyright</key><string>Copyright © Travis J. Neuman. MIT License.</string>
</dict>
</plist>
PLIST
  codesign -s - --force --deep "$AGENT_APP" 2>/dev/null || true
else
  echo "==> Skipping hotkey agent (--no-hotkey)"
fi

# Optional helper app (no global hotkey; double-click / Spotlight).
if command -v osacompile >/dev/null 2>&1; then
  osacompile -o "${APPS}/Edit Clipboard in Preview.app" <<APPLESCRIPT
on run
  do shell script "${LIBEXEC}/edit-clipboard-in-preview.sh"
end run
APPLESCRIPT
fi

echo "==> Installing LaunchAgents"
sed -e "s|__HOME__|${HOME_DIR}|g" -e "s|__STAGING__|${STAGING}|g" \
  "$ROOT/launchagents/${LABEL_CAPTURE}.plist" >"$AGENTS/${LABEL_CAPTURE}.plist"

launchctl bootout "${DOMAIN}/${LABEL_CAPTURE}" 2>/dev/null || true
launchctl bootstrap "${DOMAIN}" "$AGENTS/${LABEL_CAPTURE}.plist"

if [[ "$WITH_HOTKEY" == "1" ]]; then
  sed "s|__HOME__|${HOME_DIR}|g" \
    "$ROOT/launchagents/${LABEL_HOTKEY}.plist" >"$AGENTS/${LABEL_HOTKEY}.plist"
  launchctl bootout "${DOMAIN}/${LABEL_HOTKEY}" 2>/dev/null || true
  launchctl bootstrap "${DOMAIN}" "$AGENTS/${LABEL_HOTKEY}.plist"
else
  launchctl bootout "${DOMAIN}/${LABEL_HOTKEY}" 2>/dev/null || true
  rm -f "$AGENTS/${LABEL_HOTKEY}.plist"
fi

echo ""
echo "Installed macos-screenshot-pipeline."
echo "  Staging:     $STAGING"
echo "  Photos:      $([[ "$IMPORT_PHOTOS" == "1" ]] && echo on || echo off)"
echo "  Delete stage:$([[ "$DELETE_STAGING" == "1" ]] && echo on || echo off)"
echo "  Hotkey:      $([[ "$WITH_HOTKEY" == "1" ]] && echo '⌘⇧E' || echo disabled)"
echo "  Config:      $CONFIG_FILE"
echo "  Log:         ~/Library/Logs/macos-screenshot-pipeline.log"
echo ""
if [[ "$WITH_HOTKEY" == "1" ]]; then
  echo "Grant Accessibility to “Screenshot Pipeline Hotkey”:"
  echo "  System Settings → Privacy & Security → Accessibility"
  echo "  open \"x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility\""
  echo ""
fi
if [[ "$IMPORT_PHOTOS" == "1" ]]; then
  echo "First capture may prompt to allow Automation control of Photos — allow it."
  echo ""
fi
if [[ "$legacy_note" == "1" ]]; then
  echo "Note: legacy agents (dev.neuman.screenshot-*) were unloaded if present."
  echo "  Old scripts may still exist under ~/.local/libexec/screenshot-to-photos"
  echo ""
fi
echo "Try: ⌘⇧4 → ⌘V    and    ⌘⇧E → markup → ⌘A ⌘C → ⌘V"
echo "Uninstall: ./uninstall.sh"
